import { createHooks } from '@wordpress/hooks';

import type { BlockEditProps as CoreBlockEditProps } from '@wordpress/blocks';
import type { FuseResultMatch } from 'fuse.js';
import type { ReactNode } from 'react';

export interface ClassPreset {
	name: string;
	description?: string;
	isDynamic?: boolean;
}

export interface CombinedClassPreset extends ClassPreset {
	isFilteredClassName?: boolean;
	id: string;
}

export interface BlockEditProps< T extends Record< string, any > >
	extends CoreBlockEditProps< T > {
	name: string;
}

export interface ModalTab {
	name: string;
	tabLabel: string;
	content: ReactNode;
}

export interface DropdownOption extends ClassPreset {
	label: string | ReactNode;
	value: string;
	__isNew__?: boolean;
	matches?: ReadonlyArray< FuseResultMatch >;
}

export interface UserSettings {
	inspectorControlPosition: 'default' | 'own-panel';
	hideThemeJSONGeneratedClasses: boolean;
	allowAddingClassNamesWithoutCreating: boolean;
}

// Generated by the wp_localize_script.
declare global {
	const cssClassManager: {
		filteredClassNames: ClassPreset[];
		userDefinedClassNames: ClassPreset[];
		userSettings: UserSettings;
		panelLabel: string;
		bodyClasses: {
			supportedPostTypes: string[];
		};
		hooks: ReturnType< typeof createHooks >;
	};
}
